export const ADD_JOB_FORM_DATA = "ADD_JOB_FORM_DATA"

export const ADD_JOB_FORM_CLIENTNAME = "ADD_JOB_FORM_CLIENTNAME"
export const ADD_JOB_FORM_CLIENTREF = "ADD_JOB_FORM_CLIENTREF"

export const ADD_JOB_FORM_SERVER = "ADD_JOB_FORM_SERVER"

export const ADD_JOB_FORM_CASENUMBER = "ADD_JOB_FORM_CASENUMBER"
export const ADD_JOB_FORM_CASEPLANTIFF = "ADD_JOB_FORM_CASEPLANTIFF"
export const ADD_JOB_FORM_CASEDEF = "ADD_JOB_FORM_CASEDEF"
export const ADD_JOB_FORM_COURTDATE = "ADD_JOB_FORM_COURTDATE"

export const ADD_JOB_FORM_COURTNAME = "ADD_JOB_FORM_COURTNAME"

export const ADD_JOB_FORM_RUSH = "ADD_JOB_FORM_RUSH"

export const ADD_JOB_FORM_DUEDATE = "ADD_JOB_FORM_DUEDATE"

export const ADD_JOB_FORM_INSTRUCTIONS = "ADD_JOB_FORM_INSTRUCTIONS"

export const ADD_JOB_FORM_PERSONSERVED = "ADD_JOB_FORM_PERSONSERVED"

export const ADD_JOB_FORM_SERVICEADDRESS = "ADD_JOB_FORM_SERVICEADDRESS"

export const ADD_JOB_FORM_SERVICE_DOCUMENTS_DESCRIPTION = "ADD_JOB_FORM_SERVICE_DOCUMENTS_DESCRIPTION"


export const ADD_JOB_FORM_SERVICE_DOCUMENTS = "ADD_JOB_FORM_SERVICE_DOCUMENTS"
export const ADD_JOB_FORM_OTHERDOCS = "ADD_JOB_FORM_OTHERDOCS"



export const ADD_JOB_FORM_SERVICEADDRESS_ADDRESS = "ADD_JOB_FORM_SERVICEADDRESS_ADDRESS"
export const ADD_JOB_FORM_SERVICEADDRESS_SUITE = "ADD_JOB_FORM_SERVICEADDRESS_SUITE"
export const ADD_JOB_FORM_SERVICEADDRESS_CITY = "ADD_JOB_FORM_SERVICEADDRESS_CITY"
export const ADD_JOB_FORM_SERVICEADDRESS_STATE = "ADD_JOB_FORM_SERVICEADDRESS_STATE"
export const ADD_JOB_FORM_SERVICEADDRESS_ZIP = "ADD_JOB_FORM_SERVICEADDRESS_ZIP"
export const ADD_JOB_FORM_SERVICEADDRESS_LAT = "ADD_JOB_FORM_SERVICEADDRESS_LAT"
export const ADD_JOB_FORM_SERVICEADDRESS_LNG = "ADD_JOB_FORM_SERVICEADDRESS_LNG"


export const ADD_JOB_FORM_INVOICE = "ADD_JOB_FORM_INVOICE"

export const ADD_JOB_FORM_INVOICE_DELETE = "ADD_JOB_FORM_INVOICE_DELETE"